// Code generated by ent, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in github.com/amr-mahmoud/mrktly/internal/infrastructure/repository/ent/runtime.go

const (
	Version = "v0.14.4"                                         // Version of ent codegen.
	Sum     = "h1:/DhDraSLXIkBhyiVoJeSshr4ZYi7femzhj6/TckzZuI=" // Sum of ent codegen.
)
