// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/amr-mahmoud/mrktly/internal/infrastructure/repository/ent/predicate"
	"github.com/amr-mahmoud/mrktly/internal/infrastructure/repository/ent/professional"
)

// ProfessionalUpdate is the builder for updating Professional entities.
type ProfessionalUpdate struct {
	config
	hooks    []Hook
	mutation *ProfessionalMutation
}

// Where appends a list predicates to the ProfessionalUpdate builder.
func (pu *ProfessionalUpdate) Where(ps ...predicate.Professional) *ProfessionalUpdate {
	pu.mutation.Where(ps...)
	return pu
}

// SetName sets the "name" field.
func (pu *ProfessionalUpdate) SetName(s string) *ProfessionalUpdate {
	pu.mutation.SetName(s)
	return pu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (pu *ProfessionalUpdate) SetNillableName(s *string) *ProfessionalUpdate {
	if s != nil {
		pu.SetName(*s)
	}
	return pu
}

// ClearName clears the value of the "name" field.
func (pu *ProfessionalUpdate) ClearName() *ProfessionalUpdate {
	pu.mutation.ClearName()
	return pu
}

// Mutation returns the ProfessionalMutation object of the builder.
func (pu *ProfessionalUpdate) Mutation() *ProfessionalMutation {
	return pu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (pu *ProfessionalUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, pu.sqlSave, pu.mutation, pu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (pu *ProfessionalUpdate) SaveX(ctx context.Context) int {
	affected, err := pu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (pu *ProfessionalUpdate) Exec(ctx context.Context) error {
	_, err := pu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pu *ProfessionalUpdate) ExecX(ctx context.Context) {
	if err := pu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (pu *ProfessionalUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(professional.Table, professional.Columns, sqlgraph.NewFieldSpec(professional.FieldID, field.TypeInt))
	if ps := pu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := pu.mutation.Name(); ok {
		_spec.SetField(professional.FieldName, field.TypeString, value)
	}
	if pu.mutation.NameCleared() {
		_spec.ClearField(professional.FieldName, field.TypeString)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, pu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{professional.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	pu.mutation.done = true
	return n, nil
}

// ProfessionalUpdateOne is the builder for updating a single Professional entity.
type ProfessionalUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProfessionalMutation
}

// SetName sets the "name" field.
func (puo *ProfessionalUpdateOne) SetName(s string) *ProfessionalUpdateOne {
	puo.mutation.SetName(s)
	return puo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (puo *ProfessionalUpdateOne) SetNillableName(s *string) *ProfessionalUpdateOne {
	if s != nil {
		puo.SetName(*s)
	}
	return puo
}

// ClearName clears the value of the "name" field.
func (puo *ProfessionalUpdateOne) ClearName() *ProfessionalUpdateOne {
	puo.mutation.ClearName()
	return puo
}

// Mutation returns the ProfessionalMutation object of the builder.
func (puo *ProfessionalUpdateOne) Mutation() *ProfessionalMutation {
	return puo.mutation
}

// Where appends a list predicates to the ProfessionalUpdate builder.
func (puo *ProfessionalUpdateOne) Where(ps ...predicate.Professional) *ProfessionalUpdateOne {
	puo.mutation.Where(ps...)
	return puo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (puo *ProfessionalUpdateOne) Select(field string, fields ...string) *ProfessionalUpdateOne {
	puo.fields = append([]string{field}, fields...)
	return puo
}

// Save executes the query and returns the updated Professional entity.
func (puo *ProfessionalUpdateOne) Save(ctx context.Context) (*Professional, error) {
	return withHooks(ctx, puo.sqlSave, puo.mutation, puo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (puo *ProfessionalUpdateOne) SaveX(ctx context.Context) *Professional {
	node, err := puo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (puo *ProfessionalUpdateOne) Exec(ctx context.Context) error {
	_, err := puo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (puo *ProfessionalUpdateOne) ExecX(ctx context.Context) {
	if err := puo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (puo *ProfessionalUpdateOne) sqlSave(ctx context.Context) (_node *Professional, err error) {
	_spec := sqlgraph.NewUpdateSpec(professional.Table, professional.Columns, sqlgraph.NewFieldSpec(professional.FieldID, field.TypeInt))
	id, ok := puo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Professional.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := puo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, professional.FieldID)
		for _, f := range fields {
			if !professional.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != professional.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := puo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := puo.mutation.Name(); ok {
		_spec.SetField(professional.FieldName, field.TypeString, value)
	}
	if puo.mutation.NameCleared() {
		_spec.ClearField(professional.FieldName, field.TypeString)
	}
	_node = &Professional{config: puo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, puo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{professional.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	puo.mutation.done = true
	return _node, nil
}
