// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Customer is the predicate function for customer builders.
type Customer func(*sql.Selector)

// Professional is the predicate function for professional builders.
type Professional func(*sql.Selector)

// Topic is the predicate function for topic builders.
type Topic func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
